<?php
declare(strict_types=1);

use Hyva\CmsLiveviewEditor\Block\Element;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var Element $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels*/
?>
<div
    class="size-4 rounded-full bg-red-500 absolute"
    data-liveview-element="stl-single"
    style="top:<?= $block->getYAxis() ?>%;left:<?= $block->getXAxis() ?>%"
    <?= /** @noEscape */ $block->getEditorAttrs() ?>
    <?= /** @noEscape */ $block->renderBlockId() ?>
></div>
